### ISSUE TITLE
Hi  how can I use template in Underscore.cs

### ISSUE THREAD

**Issue by astw** [konkked/Underscore.cs#53]
Hi,  I would like to use Underscore.cs to generate html content,  just like in Underscore.js way below

_.templateSettings.variable = "rc";

in html file, I can access listTitle associated with rc variable. 
  
        <h2>
            <%- rc.listTitle %>
        </h2>
 
More information, please check 
http://www.bennadel.com/blog/2411-using-underscore-js-templates-to-render-html-partials.htm

Does Underscore.cs support this kind of usage now?

**Comment by zckeyser** [comment]
It does not. This library is currently focused on being a general utility rather than focusing on web-specific issues such as HTML templating. C# already has support for that kind of templating with libraries/frameworks such as ASP.NET MVC with Razor templates, and in order for us to do something like that we'd basically need to turn this into a bona fide templating framework which isn't really what we're going for.
